export enum AnalysisType {
    SALES_BY_MONTH = "SALES_BY_MONTH",
    SALES_BY_WEEK = "SALES_BY_WEEK",
    SALES_BY_YEAR = "SALES_BY_YEAR",
    TOTAL_SALES = "TOTAL_SALES",
    SALES_TREND = "SALES_TREND",
    TOP_10_PERFUMES = "TOP_10_PERFUMES",
    TOP_10_REVENUE = "TOP_10_REVENUE"
}
